BEGIN ;

DROP TABLE IF EXISTS "plats",
"vignettes",
"accompagnements",
"plats_has_accompagnements",
"plats_has_vignettes" ;


CREATE TABLE IF NOT EXISTS "plats" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom" TEXT NOT NULL,
    "recette" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "prix" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "vignettes" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom" TEXT NOT NULL,
    "icone" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "accompagnements" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nom" TEXT NOT NULL,
    "couleur" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "plats_has_vignettes" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "plats_id" INTEGER NOT NULL REFERENCES "plats"("id") ON DELETE CASCADE,
    "vignettes_id" INTEGER NOT NULL REFERENCES "vignettes"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "plats_has_accompagnements" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "plats_id" INTEGER NOT NULL REFERENCES "plats"("id") ON DELETE CASCADE,
    "accompagnements_id" INTEGER NOT NULL REFERENCES "accompagnements"("id") ON DELETE CASCADE
);

COMMIT ;